# Generated by Django 5.2.3 on 2025-07-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Descrição do Ativo')),
                ('codigo_patrimonio', models.CharField(max_length=100, unique=True, verbose_name='Tombo')),
                ('status', models.CharField(choices=[('OPERACAO', 'Em Operação'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Fora de Operação')], default='OPERACAO', max_length=20, verbose_name='Status')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.sala', verbose_name='Localização (Sala)')),
                ('tipo_ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoativo', verbose_name='Tipo de Ativo')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
            },
        ),
    ]
