# Generated by Django 5.2.3 on 2025-07-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Bloco')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoForro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Forro',
                'verbose_name_plural': 'Tipos de Forro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Pintura',
                'verbose_name_plural': 'Tipos de Pintura',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Piso',
                'verbose_name_plural': 'Tipos de Pisos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Porta',
                'verbose_name_plural': 'Tipos de Porta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Número da Sala')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Metragem (m²)')),
                ('qtd_luminarias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Luminárias')),
                ('qtd_tomadas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Tomadas')),
                ('qtd_interruptores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Interruptores')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.bloco', verbose_name='Bloco')),
                ('tipo_forro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoforro', verbose_name='Tipo de Forro')),
                ('tipo_pintura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipopintura', verbose_name='Tipo de Pintura')),
                ('tipo_piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipopiso', verbose_name='Tipo de Piso')),
                ('tipo_porta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoporta', verbose_name='Tipo de Porta')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['bloco__nome', 'nome'],
                'unique_together': {('bloco', 'nome')},
            },
        ),
    ]
