# Generated by Django 5.2.3 on 2025-07-02 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_solicitante', models.EmailField(max_length=255, verbose_name='E-mail do Solicitante')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Serviço')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_chamados/', verbose_name='Foto')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('observacoes_tecnicas', models.TextField(blank=True, null=True, verbose_name='Observações Técnicas')),
                ('data_visita', models.DateField(blank=True, null=True, verbose_name='Data da Visita Agendada')),
                ('avaliacao', models.IntegerField(blank=True, null=True, verbose_name='Avaliação (1-5)')),
                ('comentario_avaliacao', models.TextField(blank=True, null=True, verbose_name='Comentário da Avaliação')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.bloco', verbose_name='Bloco do Serviço')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.sala', verbose_name='Sala do Serviço')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tiposervico', verbose_name='Tipo de Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_interacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='chamados.chamado', verbose_name='Chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Interno')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['data_interacao'],
            },
        ),
    ]
