# Generated by Django 5.2.3 on 2025-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificação'),
        ),
    ]
