# Generated by Django 5.2.3 on 2025-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_data_modificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('DESIGNADO', 'Designado'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ARQUIVADO', 'Arquivado')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
    ]
